name: Build
on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout blog and theme
      uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Installation hugo
      run: go install github.com/gohugoio/hugo

    - name: Build site
      run: hugo --config=config.toml,google_analytics.toml
