name: Build
on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout blog and theme
      uses: actions/checkout@v1
      with:
        submodules: recursive
        
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.59.1'

    - name: Build
      run: hugo --config=config.toml,google_analytics.toml
      
    - name: Publish
      uses: peaceiris/actions-gh-pages@v2
      env:
        EXTERNAL_REPOSITORY: vazrupe/vazrupe.github.io
        ACTIONS_DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        PUBLISH_BRANCH: master
        PUBLISH_DIR: ./public
